### PR TITLE
My first bloody commit bruh

### PR DESCRIPTION
**Pull request by tgv2002**
Hey Arjun!
check out my first pull request dude!

### CODE REVIEW

**Comment by tharjun** [comment]
Happy to see it. Congrats. But I will give you an issue. Love the commit msg by the way.

**Review by tharjun — CHANGES_REQUESTED** [review]
Issue 1: I hate .txt files on my repos. Covert it into markdown. It looks nice on git.  Also add a funny meme. Search on google how to add images in mark down. Practice for ISS.

**Comment by tgv2002** [comment]
hey!
Just check if that was what you needed.
thanks.

**Review by tharjun — COMMENTED** [review]
I want Markdown not html. Html sucks on git

**Review by tharjun — CHANGES_REQUESTED** [review]
I want markdown for image

**Review by tharjun — APPROVED** [review]
Great Job.

**Comment by tgv2002** [comment]
yay!

**Pull request merged**
